[project]
name = "rimpack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Natalia Borovskikh", email = "lai.tash@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pydantic>=2.13,<3",
    "strictyaml>=1.7.3,<2",
]

[dependency-groups]
dev = [
    "basedpyright",
    "prek",
    "pytest>=9.1.1",
    "ruff",
]

[project.scripts]
rimpack = "rimpack:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.basedpyright]
include = ["src"]
pythonVersion = "3.14"
typeCheckingMode = "standard"

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]
